const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Behaviors.scrollto,
		C3.Behaviors.destroy,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Platform.Acts.FallThrough,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.OnLayoutEnd
	];
};
self.C3_JsPropNameTable = [
	{Teclado: 0},
	{Mosaico: 0},
	{Sólido: 0},
	{Espinhos: 0},
	{Janela: 0},
	{Suporte: 0},
	{Porta: 0},
	{Plataforma: 0},
	{Caixa: 0},
	{Piscar: 0},
	{Bau: 0},
	{Chave: 0},
	{Bomba: 0},
	{CentrarEm: 0},
	{DestruirForaDoLayout: 0},
	{Jogador: 0},
	{Sensor: 0},
	{Cacto: 0},
	{Moeda: 0},
	{Direcao: 0},
	{Inimigo: 0},
	{Sensor_Direita: 0},
	{Sensor_Esquerda: 0},
	{Âncora: 0},
	{Pontuação: 0},
	{Áudio: 0},
	{início: 0},
	{Restart: 0},
	{Final: 0},
	{Pontos: 0},
	{Vida: 0}
];

self.InstanceType = {
	Teclado: class extends self.IInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	Espinhos: class extends self.ISpriteInstance {},
	Janela: class extends self.ISpriteInstance {},
	Suporte: class extends self.ISpriteInstance {},
	Porta: class extends self.ISpriteInstance {},
	Caixa: class extends self.ISpriteInstance {},
	Bau: class extends self.ISpriteInstance {},
	Jogador: class extends self.ISpriteInstance {},
	Sensor: class extends self.ISpriteInstance {},
	Cacto: class extends self.ISpriteInstance {},
	Moeda: class extends self.ISpriteInstance {},
	Chave: class extends self.ISpriteInstance {},
	Inimigo: class extends self.ISpriteInstance {},
	Sensor_Direita: class extends self.ISpriteInstance {},
	Sensor_Esquerda: class extends self.ISpriteInstance {},
	Bomba: class extends self.ISpriteInstance {},
	Pontuação: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	início: class extends self.ISpriteInstance {},
	Restart: class extends self.ISpriteInstance {},
	Final: class extends self.ISpriteInstance {}
}